package com.jmamoon;

import com.jmamoon.socialhousingcreditsystem.entity.*;
import com.jmamoon.socialhousingcreditsystem.constants.Constants;

rule "person whose age is less than legal adult age"
    salience 200
    when
        creditRequest : CreditRequest();
        person : Person ( age < Constants.LEGAL_ADULT_AGE ) from creditRequest.getPerson();
    then
        creditRequest.addIssue(Constants.PERSON_YOUNG);
end

rule "person whose age is more than maximum age"
    salience 200
    when
        creditRequest : CreditRequest();
        person : Person ( age > Constants.MAX_AGE ) from creditRequest.getPerson();
    then
        creditRequest.addIssue(Constants.PERSON_OLD);
end

rule "person whose age is less or equal than breakpoint age"
    salience 100
    when
        creditRequest : CreditRequest();

        person : Person ( age <= Constants.BREAKPOINT_AGE ) from creditRequest.getPerson();
        personAffordablePayment : Double () from person.getAmountPerMonth();

        property : Property (price > personAffordablePayment * Constants.MONTHS * Constants.YEARS_TO_PAY_YOUNG_PERSON ) from creditRequest.getProperty();

    then
        creditRequest.addIssue("Property is too expensive");
end

rule "person whose age is more than breakpoint age"
    salience 100
    when
        creditRequest : CreditRequest();

        person : Person ( age > Constants.BREAKPOINT_AGE ) from creditRequest.getPerson();
        personAffordablePayment : Double () from person.getAmountPerMonth();

        property : Property (price > personAffordablePayment * Constants.MONTHS * Constants.YEARS_TO_PAY_OLD_PERSON ) from creditRequest.getProperty();

    then
        creditRequest.addIssue(Constants.PROPERTY_EXPENSIVE);
end
